dockeep-env-vars:
#  KAFKA_BOOTSTRAP_SERVERS:
#  REDIS_HOST:
#  REDIS_PORT:
  DB_URL:
  DB_USERNAME:
  DB_PASSWORD:
  DB_DRIVER:
  DB_MAX_POOL_SIZE:
  DB_MIN_IDLE_CONNECTIONS:
  DB_IDLE_TIMEOUT_MS:
  DB_MAX_LIFETIME_MS:

  AWS_ACCESS_KEY:
  AWS_SECRET_KEY:
  AWS_REGION:
  AWS_BUCKET_NAME: